/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_wspec (void);
GtkWidget* create_wpar (void);
GtkWidget* create_wmain (void);
GtkWidget* create_wabout (void);
GtkWidget* create_wmonitor (void);
