/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/stat.h>
#include <unistd.h>
#include <string.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

GtkWidget*
create_wspec ()
{
  GtkWidget *wspec;
  GtkWidget *vbox1;
  GtkWidget *hbox1;
  GtkWidget *label1;
  GtkWidget *specfreqpointer;
  GtkWidget *label2;
  GtkWidget *specfreqmark;
  GtkWidget *label3;
  GtkWidget *specfreqspace;
  GtkWidget *frame1;
  GtkWidget *hbox2;
  GSList *hbox2_group = NULL;
  GtkWidget *shift170;
  GtkWidget *shift200;
  GtkWidget *shift425;
  GtkWidget *shift800;
  GtkWidget *frame4;
  GtkWidget *spec;

  wspec = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_object_set_data (GTK_OBJECT (wspec), "wspec", wspec);
  gtk_window_set_title (GTK_WINDOW (wspec), _("Spectrum Display"));
  gtk_window_set_policy (GTK_WINDOW (wspec), FALSE, FALSE, FALSE);
  gtk_window_set_wmclass (GTK_WINDOW (wspec), "hfterm", "hfterm");

  vbox1 = gtk_vbox_new (FALSE, 0);
  gtk_widget_ref (vbox1);
  gtk_object_set_data_full (GTK_OBJECT (wspec), "vbox1", vbox1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (vbox1);
  gtk_container_add (GTK_CONTAINER (wspec), vbox1);

  hbox1 = gtk_hbox_new (FALSE, 0);
  gtk_widget_ref (hbox1);
  gtk_object_set_data_full (GTK_OBJECT (wspec), "hbox1", hbox1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hbox1);
  gtk_box_pack_start (GTK_BOX (vbox1), hbox1, FALSE, TRUE, 0);

  label1 = gtk_label_new (_("Pointer"));
  gtk_widget_ref (label1);
  gtk_object_set_data_full (GTK_OBJECT (wspec), "label1", label1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label1);
  gtk_box_pack_start (GTK_BOX (hbox1), label1, FALSE, FALSE, 0);

  specfreqpointer = gtk_entry_new ();
  gtk_widget_ref (specfreqpointer);
  gtk_object_set_data_full (GTK_OBJECT (wspec), "specfreqpointer", specfreqpointer,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (specfreqpointer);
  gtk_box_pack_start (GTK_BOX (hbox1), specfreqpointer, FALSE, TRUE, 4);
  gtk_widget_set_usize (specfreqpointer, 60, -2);
  GTK_WIDGET_UNSET_FLAGS (specfreqpointer, GTK_CAN_FOCUS);
  gtk_entry_set_editable (GTK_ENTRY (specfreqpointer), FALSE);

  label2 = gtk_label_new (_("Mark"));
  gtk_widget_ref (label2);
  gtk_object_set_data_full (GTK_OBJECT (wspec), "label2", label2,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label2);
  gtk_box_pack_start (GTK_BOX (hbox1), label2, FALSE, FALSE, 0);

  specfreqmark = gtk_entry_new ();
  gtk_widget_ref (specfreqmark);
  gtk_object_set_data_full (GTK_OBJECT (wspec), "specfreqmark", specfreqmark,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (specfreqmark);
  gtk_box_pack_start (GTK_BOX (hbox1), specfreqmark, FALSE, TRUE, 4);
  gtk_widget_set_usize (specfreqmark, 60, -2);
  GTK_WIDGET_UNSET_FLAGS (specfreqmark, GTK_CAN_FOCUS);
  gtk_entry_set_editable (GTK_ENTRY (specfreqmark), FALSE);

  label3 = gtk_label_new (_("Space"));
  gtk_widget_ref (label3);
  gtk_object_set_data_full (GTK_OBJECT (wspec), "label3", label3,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label3);
  gtk_box_pack_start (GTK_BOX (hbox1), label3, FALSE, FALSE, 0);

  specfreqspace = gtk_entry_new ();
  gtk_widget_ref (specfreqspace);
  gtk_object_set_data_full (GTK_OBJECT (wspec), "specfreqspace", specfreqspace,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (specfreqspace);
  gtk_box_pack_start (GTK_BOX (hbox1), specfreqspace, FALSE, TRUE, 4);
  gtk_widget_set_usize (specfreqspace, 60, -2);
  GTK_WIDGET_UNSET_FLAGS (specfreqspace, GTK_CAN_FOCUS);
  gtk_entry_set_editable (GTK_ENTRY (specfreqspace), FALSE);

  frame1 = gtk_frame_new (_("Shift"));
  gtk_widget_ref (frame1);
  gtk_object_set_data_full (GTK_OBJECT (wspec), "frame1", frame1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (frame1);
  gtk_box_pack_end (GTK_BOX (hbox1), frame1, FALSE, TRUE, 0);

  hbox2 = gtk_hbox_new (FALSE, 0);
  gtk_widget_ref (hbox2);
  gtk_object_set_data_full (GTK_OBJECT (wspec), "hbox2", hbox2,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hbox2);
  gtk_container_add (GTK_CONTAINER (frame1), hbox2);

  shift170 = gtk_radio_button_new_with_label (hbox2_group, _("170"));
  hbox2_group = gtk_radio_button_group (GTK_RADIO_BUTTON (shift170));
  gtk_widget_ref (shift170);
  gtk_object_set_data_full (GTK_OBJECT (wspec), "shift170", shift170,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (shift170);
  gtk_box_pack_start (GTK_BOX (hbox2), shift170, FALSE, FALSE, 0);

  shift200 = gtk_radio_button_new_with_label (hbox2_group, _("200"));
  hbox2_group = gtk_radio_button_group (GTK_RADIO_BUTTON (shift200));
  gtk_widget_ref (shift200);
  gtk_object_set_data_full (GTK_OBJECT (wspec), "shift200", shift200,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (shift200);
  gtk_box_pack_start (GTK_BOX (hbox2), shift200, FALSE, FALSE, 0);

  shift425 = gtk_radio_button_new_with_label (hbox2_group, _("425"));
  hbox2_group = gtk_radio_button_group (GTK_RADIO_BUTTON (shift425));
  gtk_widget_ref (shift425);
  gtk_object_set_data_full (GTK_OBJECT (wspec), "shift425", shift425,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (shift425);
  gtk_box_pack_start (GTK_BOX (hbox2), shift425, FALSE, FALSE, 0);

  shift800 = gtk_radio_button_new_with_label (hbox2_group, _("800"));
  hbox2_group = gtk_radio_button_group (GTK_RADIO_BUTTON (shift800));
  gtk_widget_ref (shift800);
  gtk_object_set_data_full (GTK_OBJECT (wspec), "shift800", shift800,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (shift800);
  gtk_box_pack_start (GTK_BOX (hbox2), shift800, FALSE, FALSE, 0);

  frame4 = gtk_frame_new (_("Spectrum"));
  gtk_widget_ref (frame4);
  gtk_object_set_data_full (GTK_OBJECT (wspec), "frame4", frame4,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (frame4);
  gtk_box_pack_start (GTK_BOX (vbox1), frame4, FALSE, FALSE, 0);

  spec = spectrum_new ("spec", NULL, NULL, 0, 0);
  gtk_widget_ref (spec);
  gtk_object_set_data_full (GTK_OBJECT (wspec), "spec", spec,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (spec);
  gtk_container_add (GTK_CONTAINER (frame4), spec);
  gtk_widget_set_usize (spec, 512, 384);
  GTK_WIDGET_SET_FLAGS (spec, GTK_CAN_FOCUS);
  GTK_WIDGET_UNSET_FLAGS (spec, GTK_CAN_DEFAULT);
  gtk_widget_set_events (spec, GDK_POINTER_MOTION_MASK | GDK_BUTTON_PRESS_MASK);

  gtk_signal_connect (GTK_OBJECT (wspec), "delete_event",
                      GTK_SIGNAL_FUNC (on_wspec_delete_event),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (spec), "button_press_event",
                      GTK_SIGNAL_FUNC (on_spec_button_press_event),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (spec), "motion_notify_event",
                      GTK_SIGNAL_FUNC (on_spec_motion_event),
                      NULL);

  return wspec;
}

GtkWidget*
create_wpar ()
{
  GtkWidget *wpar;
  GtkWidget *vbox2;
  GtkWidget *notebook1;
  GtkWidget *table6;
  GtkWidget *label28;
  GtkWidget *label27;
  GtkWidget *fskmark;
  GList *fskmark_items = NULL;
  GtkWidget *fskmarkfreq;
  GtkWidget *fskspace;
  GList *fskspace_items = NULL;
  GtkWidget *fskspacefreq;
  GtkWidget *label4;
  GtkWidget *table4;
  GtkWidget *label22;
  GtkWidget *rttyinvert;
  GtkWidget *rttyrxtxinvert;
  GtkWidget *rttybaudrate;
  GtkWidget *label5;
  GtkWidget *table3;
  GtkWidget *label21;
  GtkWidget *label20;
  GtkWidget *label19;
  GtkWidget *label18;
  GtkWidget *label17;
  GtkWidget *amtorrxtxinvert;
  GtkWidget *amtorinvert;
  GtkWidget *amtordestcall;
  GtkWidget *amtorselfeccall;
  GtkWidget *amtormycall;
  GtkWidget *amtortxdelay;
  GtkWidget *amtorretry;
  GtkWidget *label6;
  GtkWidget *hbox3;
  GtkWidget *frame3;
  GtkWidget *table2;
  GtkWidget *label14;
  GtkWidget *label15;
  GtkWidget *label16;
  GtkWidget *pactorlongpath;
  GtkWidget *pactorcall;
  GtkWidget *pactormycall;
  GtkWidget *pactortxdelay;
  GtkWidget *pactorretry;
  GtkWidget *label13;
  GtkWidget *label31;
  GtkWidget *frame2;
  GtkWidget *table1;
  GtkWidget *pactorcrc0;
  GtkWidget *pactorcrc1;
  GtkWidget *pactorcrc3;
  GtkWidget *pactorcrc2;
  GtkWidget *label9;
  GtkWidget *label10;
  GtkWidget *label11;
  GtkWidget *label12;
  GtkWidget *label7;
  GtkWidget *table5;
  GtkWidget *gtordestcall;
  GtkWidget *gtormycall;
  GtkWidget *gtortxdelay;
  GtkWidget *gtorretry;
  GtkWidget *label23;
  GtkWidget *label24;
  GtkWidget *label25;
  GtkWidget *label26;
  GtkWidget *label8;
  GtkWidget *toolbar1;
  GtkWidget *parok;
  GtkWidget *parcancel;

  wpar = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_object_set_data (GTK_OBJECT (wpar), "wpar", wpar);
  gtk_window_set_title (GTK_WINDOW (wpar), _("Parameters"));
  gtk_window_set_policy (GTK_WINDOW (wpar), FALSE, TRUE, TRUE);
  gtk_window_set_wmclass (GTK_WINDOW (wpar), "hfterm", "hfterm");

  vbox2 = gtk_vbox_new (FALSE, 0);
  gtk_widget_ref (vbox2);
  gtk_object_set_data_full (GTK_OBJECT (wpar), "vbox2", vbox2,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (vbox2);
  gtk_container_add (GTK_CONTAINER (wpar), vbox2);

  notebook1 = gtk_notebook_new ();
  gtk_widget_ref (notebook1);
  gtk_object_set_data_full (GTK_OBJECT (wpar), "notebook1", notebook1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (notebook1);
  gtk_box_pack_start (GTK_BOX (vbox2), notebook1, TRUE, TRUE, 0);

  table6 = gtk_table_new (2, 2, FALSE);
  gtk_widget_ref (table6);
  gtk_object_set_data_full (GTK_OBJECT (wpar), "table6", table6,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (table6);
  gtk_container_add (GTK_CONTAINER (notebook1), table6);

  label28 = gtk_label_new (_("Mark Frequency"));
  gtk_widget_ref (label28);
  gtk_object_set_data_full (GTK_OBJECT (wpar), "label28", label28,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label28);
  gtk_table_attach (GTK_TABLE (table6), label28, 0, 1, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label28), 0, 0.5);
  gtk_misc_set_padding (GTK_MISC (label28), 5, 0);

  label27 = gtk_label_new (_("Space Frequency"));
  gtk_widget_ref (label27);
  gtk_object_set_data_full (GTK_OBJECT (wpar), "label27", label27,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label27);
  gtk_table_attach (GTK_TABLE (table6), label27, 0, 1, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label27), 0, 0.5);
  gtk_misc_set_padding (GTK_MISC (label27), 5, 0);

  fskmark = gtk_combo_new ();
  gtk_widget_ref (fskmark);
  gtk_object_set_data_full (GTK_OBJECT (wpar), "fskmark", fskmark,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (fskmark);
  gtk_table_attach (GTK_TABLE (table6), fskmark, 1, 2, 1, 2,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_SHRINK | GTK_FILL),
                    (GtkAttachOptions) (0), 3, 3);
  fskmark_items = g_list_append (fskmark_items, _("1800"));
  fskmark_items = g_list_append (fskmark_items, _("2400"));
  gtk_combo_set_popdown_strings (GTK_COMBO (fskmark), fskmark_items);
  g_list_free (fskmark_items);

  fskmarkfreq = GTK_COMBO (fskmark)->entry;
  gtk_widget_ref (fskmarkfreq);
  gtk_object_set_data_full (GTK_OBJECT (wpar), "fskmarkfreq", fskmarkfreq,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (fskmarkfreq);
  gtk_entry_set_text (GTK_ENTRY (fskmarkfreq), _("1800"));

  fskspace = gtk_combo_new ();
  gtk_widget_ref (fskspace);
  gtk_object_set_data_full (GTK_OBJECT (wpar), "fskspace", fskspace,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (fskspace);
  gtk_table_attach (GTK_TABLE (table6), fskspace, 1, 2, 0, 1,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_SHRINK | GTK_FILL),
                    (GtkAttachOptions) (0), 3, 3);
  fskspace_items = g_list_append (fskspace_items, _("1600"));
  fskspace_items = g_list_append (fskspace_items, _("2200"));
  gtk_combo_set_popdown_strings (GTK_COMBO (fskspace), fskspace_items);
  g_list_free (fskspace_items);

  fskspacefreq = GTK_COMBO (fskspace)->entry;
  gtk_widget_ref (fskspacefreq);
  gtk_object_set_data_full (GTK_OBJECT (wpar), "fskspacefreq", fskspacefreq,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (fskspacefreq);
  gtk_entry_set_text (GTK_ENTRY (fskspacefreq), _("1600"));

  label4 = gtk_label_new (_("FSK"));
  gtk_widget_ref (label4);
  gtk_object_set_data_full (GTK_OBJECT (wpar), "label4", label4,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label4);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 0), label4);

  table4 = gtk_table_new (3, 2, FALSE);
  gtk_widget_ref (table4);
  gtk_object_set_data_full (GTK_OBJECT (wpar), "table4", table4,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (table4);
  gtk_container_add (GTK_CONTAINER (notebook1), table4);

  label22 = gtk_label_new (_("Baud Rate"));
  gtk_widget_ref (label22);
  gtk_object_set_data_full (GTK_OBJECT (wpar), "label22", label22,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label22);
  gtk_table_attach (GTK_TABLE (table4), label22, 0, 1, 0, 1,
                    (GtkAttachOptions) (0),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label22), 0, 0.5);
  gtk_misc_set_padding (GTK_MISC (label22), 5, 0);

  rttyinvert = gtk_check_button_new_with_label (_("Invert"));
  gtk_widget_ref (rttyinvert);
  gtk_object_set_data_full (GTK_OBJECT (wpar), "rttyinvert", rttyinvert,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (rttyinvert);
  gtk_table_attach (GTK_TABLE (table4), rttyinvert, 1, 2, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 3, 3);

  rttyrxtxinvert = gtk_check_button_new_with_label (_("RX/TX invert"));
  gtk_widget_ref (rttyrxtxinvert);
  gtk_object_set_data_full (GTK_OBJECT (wpar), "rttyrxtxinvert", rttyrxtxinvert,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (rttyrxtxinvert);
  gtk_table_attach (GTK_TABLE (table4), rttyrxtxinvert, 1, 2, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 3, 3);

  rttybaudrate = gtk_entry_new_with_max_length (5);
  gtk_widget_ref (rttybaudrate);
  gtk_object_set_data_full (GTK_OBJECT (wpar), "rttybaudrate", rttybaudrate,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (rttybaudrate);
  gtk_table_attach (GTK_TABLE (table4), rttybaudrate, 1, 2, 0, 1,
                    (GtkAttachOptions) (GTK_SHRINK | GTK_FILL),
                    (GtkAttachOptions) (0), 3, 3);
  gtk_entry_set_text (GTK_ENTRY (rttybaudrate), _("45"));

  label5 = gtk_label_new (_("RTTY"));
  gtk_widget_ref (label5);
  gtk_object_set_data_full (GTK_OBJECT (wpar), "label5", label5,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label5);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 1), label5);

  table3 = gtk_table_new (7, 2, FALSE);
  gtk_widget_ref (table3);
  gtk_object_set_data_full (GTK_OBJECT (wpar), "table3", table3,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (table3);
  gtk_container_add (GTK_CONTAINER (notebook1), table3);

  label21 = gtk_label_new (_("Retries"));
  gtk_widget_ref (label21);
  gtk_object_set_data_full (GTK_OBJECT (wpar), "label21", label21,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label21);
  gtk_table_attach (GTK_TABLE (table3), label21, 0, 1, 4, 5,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label21), 0, 0.5);
  gtk_misc_set_padding (GTK_MISC (label21), 5, 0);

  label20 = gtk_label_new (_("TX Delay (ms)"));
  gtk_widget_ref (label20);
  gtk_object_set_data_full (GTK_OBJECT (wpar), "label20", label20,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label20);
  gtk_table_attach (GTK_TABLE (table3), label20, 0, 1, 3, 4,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label20), 0, 0.5);
  gtk_misc_set_padding (GTK_MISC (label20), 5, 0);

  label19 = gtk_label_new (_("Mycall"));
  gtk_widget_ref (label19);
  gtk_object_set_data_full (GTK_OBJECT (wpar), "label19", label19,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label19);
  gtk_table_attach (GTK_TABLE (table3), label19, 0, 1, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label19), 0, 0.5);
  gtk_misc_set_padding (GTK_MISC (label19), 5, 0);

  label18 = gtk_label_new (_("Selective FEC Call"));
  gtk_widget_ref (label18);
  gtk_object_set_data_full (GTK_OBJECT (wpar), "label18", label18,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label18);
  gtk_table_attach (GTK_TABLE (table3), label18, 0, 1, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label18), 0, 0.5);
  gtk_misc_set_padding (GTK_MISC (label18), 5, 0);

  label17 = gtk_label_new (_("Destination Call"));
  gtk_widget_ref (label17);
  gtk_object_set_data_full (GTK_OBJECT (wpar), "label17", label17,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label17);
  gtk_table_attach (GTK_TABLE (table3), label17, 0, 1, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label17), 0, 0.5);
  gtk_misc_set_padding (GTK_MISC (label17), 5, 0);

  amtorrxtxinvert = gtk_check_button_new_with_label (_("RX/TX invert"));
  gtk_widget_ref (amtorrxtxinvert);
  gtk_object_set_data_full (GTK_OBJECT (wpar), "amtorrxtxinvert", amtorrxtxinvert,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (amtorrxtxinvert);
  gtk_table_attach (GTK_TABLE (table3), amtorrxtxinvert, 1, 2, 6, 7,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 3, 3);

  amtorinvert = gtk_check_button_new_with_label (_("Invert"));
  gtk_widget_ref (amtorinvert);
  gtk_object_set_data_full (GTK_OBJECT (wpar), "amtorinvert", amtorinvert,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (amtorinvert);
  gtk_table_attach (GTK_TABLE (table3), amtorinvert, 1, 2, 5, 6,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 3, 3);

  amtordestcall = gtk_entry_new_with_max_length (4);
  gtk_widget_ref (amtordestcall);
  gtk_object_set_data_full (GTK_OBJECT (wpar), "amtordestcall", amtordestcall,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (amtordestcall);
  gtk_table_attach (GTK_TABLE (table3), amtordestcall, 1, 2, 0, 1,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_SHRINK | GTK_FILL),
                    (GtkAttachOptions) (0), 3, 3);
  gtk_entry_set_text (GTK_ENTRY (amtordestcall), _("NONE"));

  amtorselfeccall = gtk_entry_new_with_max_length (4);
  gtk_widget_ref (amtorselfeccall);
  gtk_object_set_data_full (GTK_OBJECT (wpar), "amtorselfeccall", amtorselfeccall,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (amtorselfeccall);
  gtk_table_attach (GTK_TABLE (table3), amtorselfeccall, 1, 2, 1, 2,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_SHRINK | GTK_FILL),
                    (GtkAttachOptions) (0), 3, 3);
  gtk_entry_set_text (GTK_ENTRY (amtorselfeccall), _("NONE"));

  amtormycall = gtk_entry_new_with_max_length (4);
  gtk_widget_ref (amtormycall);
  gtk_object_set_data_full (GTK_OBJECT (wpar), "amtormycall", amtormycall,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (amtormycall);
  gtk_table_attach (GTK_TABLE (table3), amtormycall, 1, 2, 2, 3,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_SHRINK | GTK_FILL),
                    (GtkAttachOptions) (0), 3, 3);
  gtk_entry_set_text (GTK_ENTRY (amtormycall), _("NONE"));

  amtortxdelay = gtk_entry_new ();
  gtk_widget_ref (amtortxdelay);
  gtk_object_set_data_full (GTK_OBJECT (wpar), "amtortxdelay", amtortxdelay,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (amtortxdelay);
  gtk_table_attach (GTK_TABLE (table3), amtortxdelay, 1, 2, 3, 4,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_SHRINK | GTK_FILL),
                    (GtkAttachOptions) (0), 3, 3);
  gtk_entry_set_text (GTK_ENTRY (amtortxdelay), _("30"));

  amtorretry = gtk_entry_new ();
  gtk_widget_ref (amtorretry);
  gtk_object_set_data_full (GTK_OBJECT (wpar), "amtorretry", amtorretry,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (amtorretry);
  gtk_table_attach (GTK_TABLE (table3), amtorretry, 1, 2, 4, 5,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_SHRINK | GTK_FILL),
                    (GtkAttachOptions) (0), 3, 3);
  gtk_entry_set_text (GTK_ENTRY (amtorretry), _("30"));

  label6 = gtk_label_new (_("Amtor"));
  gtk_widget_ref (label6);
  gtk_object_set_data_full (GTK_OBJECT (wpar), "label6", label6,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label6);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 2), label6);

  hbox3 = gtk_hbox_new (TRUE, 2);
  gtk_widget_ref (hbox3);
  gtk_object_set_data_full (GTK_OBJECT (wpar), "hbox3", hbox3,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hbox3);
  gtk_container_add (GTK_CONTAINER (notebook1), hbox3);

  frame3 = gtk_frame_new (_("Standard"));
  gtk_widget_ref (frame3);
  gtk_object_set_data_full (GTK_OBJECT (wpar), "frame3", frame3,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (frame3);
  gtk_box_pack_start (GTK_BOX (hbox3), frame3, TRUE, TRUE, 0);

  table2 = gtk_table_new (5, 2, FALSE);
  gtk_widget_ref (table2);
  gtk_object_set_data_full (GTK_OBJECT (wpar), "table2", table2,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (table2);
  gtk_container_add (GTK_CONTAINER (frame3), table2);

  label14 = gtk_label_new (_("Mycall"));
  gtk_widget_ref (label14);
  gtk_object_set_data_full (GTK_OBJECT (wpar), "label14", label14,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label14);
  gtk_table_attach (GTK_TABLE (table2), label14, 0, 1, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label14), 0, 0.5);
  gtk_misc_set_padding (GTK_MISC (label14), 5, 0);

  label15 = gtk_label_new (_("TX Delay (ms)"));
  gtk_widget_ref (label15);
  gtk_object_set_data_full (GTK_OBJECT (wpar), "label15", label15,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label15);
  gtk_table_attach (GTK_TABLE (table2), label15, 0, 1, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label15), 0, 0.5);
  gtk_misc_set_padding (GTK_MISC (label15), 5, 0);

  label16 = gtk_label_new (_("Retries"));
  gtk_widget_ref (label16);
  gtk_object_set_data_full (GTK_OBJECT (wpar), "label16", label16,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label16);
  gtk_table_attach (GTK_TABLE (table2), label16, 0, 1, 3, 4,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label16), 0, 0.5);
  gtk_misc_set_padding (GTK_MISC (label16), 5, 0);

  pactorlongpath = gtk_check_button_new_with_label (_("Longpath"));
  gtk_widget_ref (pactorlongpath);
  gtk_object_set_data_full (GTK_OBJECT (wpar), "pactorlongpath", pactorlongpath,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (pactorlongpath);
  gtk_table_attach (GTK_TABLE (table2), pactorlongpath, 1, 2, 4, 5,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 3, 3);

  pactorcall = gtk_entry_new_with_max_length (7);
  gtk_widget_ref (pactorcall);
  gtk_object_set_data_full (GTK_OBJECT (wpar), "pactorcall", pactorcall,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (pactorcall);
  gtk_table_attach (GTK_TABLE (table2), pactorcall, 1, 2, 0, 1,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_SHRINK | GTK_FILL),
                    (GtkAttachOptions) (0), 3, 3);
  gtk_widget_set_usize (pactorcall, 10, -2);
  gtk_entry_set_text (GTK_ENTRY (pactorcall), _("NOCALL"));

  pactormycall = gtk_entry_new_with_max_length (7);
  gtk_widget_ref (pactormycall);
  gtk_object_set_data_full (GTK_OBJECT (wpar), "pactormycall", pactormycall,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (pactormycall);
  gtk_table_attach (GTK_TABLE (table2), pactormycall, 1, 2, 1, 2,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_SHRINK | GTK_FILL),
                    (GtkAttachOptions) (0), 3, 3);
  gtk_widget_set_usize (pactormycall, 10, -2);
  gtk_entry_set_text (GTK_ENTRY (pactormycall), _("NOCALL"));

  pactortxdelay = gtk_entry_new ();
  gtk_widget_ref (pactortxdelay);
  gtk_object_set_data_full (GTK_OBJECT (wpar), "pactortxdelay", pactortxdelay,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (pactortxdelay);
  gtk_table_attach (GTK_TABLE (table2), pactortxdelay, 1, 2, 2, 3,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_SHRINK | GTK_FILL),
                    (GtkAttachOptions) (0), 3, 3);
  gtk_widget_set_usize (pactortxdelay, 10, -2);
  gtk_entry_set_text (GTK_ENTRY (pactortxdelay), _("30"));

  pactorretry = gtk_entry_new ();
  gtk_widget_ref (pactorretry);
  gtk_object_set_data_full (GTK_OBJECT (wpar), "pactorretry", pactorretry,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (pactorretry);
  gtk_table_attach (GTK_TABLE (table2), pactorretry, 1, 2, 3, 4,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_SHRINK | GTK_FILL),
                    (GtkAttachOptions) (0), 3, 3);
  gtk_widget_set_usize (pactorretry, 10, -2);
  gtk_entry_set_text (GTK_ENTRY (pactorretry), _("30"));

  label13 = gtk_label_new (_("Destination Call"));
  gtk_widget_ref (label13);
  gtk_object_set_data_full (GTK_OBJECT (wpar), "label13", label13,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label13);
  gtk_table_attach (GTK_TABLE (table2), label13, 0, 1, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label13), 0, 0.5);
  gtk_misc_set_padding (GTK_MISC (label13), 5, 0);

  label31 = gtk_label_new (_("SP/LP"));
  gtk_widget_ref (label31);
  gtk_object_set_data_full (GTK_OBJECT (wpar), "label31", label31,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label31);
  gtk_table_attach (GTK_TABLE (table2), label31, 0, 1, 4, 5,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label31), 0, 0.5);
  gtk_misc_set_padding (GTK_MISC (label31), 5, 0);

  frame2 = gtk_frame_new (_("Advanced"));
  gtk_widget_ref (frame2);
  gtk_object_set_data_full (GTK_OBJECT (wpar), "frame2", frame2,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (frame2);
  gtk_box_pack_start (GTK_BOX (hbox3), frame2, TRUE, TRUE, 0);

  table1 = gtk_table_new (4, 2, FALSE);
  gtk_widget_ref (table1);
  gtk_object_set_data_full (GTK_OBJECT (wpar), "table1", table1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (table1);
  gtk_container_add (GTK_CONTAINER (frame2), table1);

  pactorcrc0 = gtk_entry_new ();
  gtk_widget_ref (pactorcrc0);
  gtk_object_set_data_full (GTK_OBJECT (wpar), "pactorcrc0", pactorcrc0,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (pactorcrc0);
  gtk_table_attach (GTK_TABLE (table1), pactorcrc0, 1, 2, 0, 1,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_SHRINK | GTK_FILL),
                    (GtkAttachOptions) (0), 3, 3);
  gtk_widget_set_usize (pactorcrc0, 10, -2);

  pactorcrc1 = gtk_entry_new ();
  gtk_widget_ref (pactorcrc1);
  gtk_object_set_data_full (GTK_OBJECT (wpar), "pactorcrc1", pactorcrc1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (pactorcrc1);
  gtk_table_attach (GTK_TABLE (table1), pactorcrc1, 1, 2, 1, 2,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_SHRINK | GTK_FILL),
                    (GtkAttachOptions) (0), 3, 3);
  gtk_widget_set_usize (pactorcrc1, 10, -2);

  pactorcrc3 = gtk_entry_new ();
  gtk_widget_ref (pactorcrc3);
  gtk_object_set_data_full (GTK_OBJECT (wpar), "pactorcrc3", pactorcrc3,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (pactorcrc3);
  gtk_table_attach (GTK_TABLE (table1), pactorcrc3, 1, 2, 3, 4,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_SHRINK | GTK_FILL),
                    (GtkAttachOptions) (0), 3, 3);
  gtk_widget_set_usize (pactorcrc3, 10, -2);

  pactorcrc2 = gtk_entry_new ();
  gtk_widget_ref (pactorcrc2);
  gtk_object_set_data_full (GTK_OBJECT (wpar), "pactorcrc2", pactorcrc2,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (pactorcrc2);
  gtk_table_attach (GTK_TABLE (table1), pactorcrc2, 1, 2, 2, 3,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_SHRINK | GTK_FILL),
                    (GtkAttachOptions) (0), 3, 3);
  gtk_widget_set_usize (pactorcrc2, 10, -2);

  label9 = gtk_label_new (_("CRC 100 Chg"));
  gtk_widget_ref (label9);
  gtk_object_set_data_full (GTK_OBJECT (wpar), "label9", label9,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label9);
  gtk_table_attach (GTK_TABLE (table1), label9, 0, 1, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label9), 0, 0.5);
  gtk_misc_set_padding (GTK_MISC (label9), 5, 0);

  label10 = gtk_label_new (_("CRC 100"));
  gtk_widget_ref (label10);
  gtk_object_set_data_full (GTK_OBJECT (wpar), "label10", label10,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label10);
  gtk_table_attach (GTK_TABLE (table1), label10, 0, 1, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_label_set_justify (GTK_LABEL (label10), GTK_JUSTIFY_LEFT);
  gtk_misc_set_alignment (GTK_MISC (label10), 0, 0.5);
  gtk_misc_set_padding (GTK_MISC (label10), 5, 0);

  label11 = gtk_label_new (_("CRC 200 Chg"));
  gtk_widget_ref (label11);
  gtk_object_set_data_full (GTK_OBJECT (wpar), "label11", label11,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label11);
  gtk_table_attach (GTK_TABLE (table1), label11, 0, 1, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label11), 0, 0.5);
  gtk_misc_set_padding (GTK_MISC (label11), 5, 0);

  label12 = gtk_label_new (_("CRC 200"));
  gtk_widget_ref (label12);
  gtk_object_set_data_full (GTK_OBJECT (wpar), "label12", label12,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label12);
  gtk_table_attach (GTK_TABLE (table1), label12, 0, 1, 3, 4,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label12), 0, 0.5);
  gtk_misc_set_padding (GTK_MISC (label12), 5, 0);

  label7 = gtk_label_new (_("Pactor"));
  gtk_widget_ref (label7);
  gtk_object_set_data_full (GTK_OBJECT (wpar), "label7", label7,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label7);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 3), label7);

  table5 = gtk_table_new (4, 2, FALSE);
  gtk_widget_ref (table5);
  gtk_object_set_data_full (GTK_OBJECT (wpar), "table5", table5,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (table5);
  gtk_container_add (GTK_CONTAINER (notebook1), table5);

  gtordestcall = gtk_entry_new_with_max_length (12);
  gtk_widget_ref (gtordestcall);
  gtk_object_set_data_full (GTK_OBJECT (wpar), "gtordestcall", gtordestcall,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (gtordestcall);
  gtk_table_attach (GTK_TABLE (table5), gtordestcall, 1, 2, 0, 1,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_SHRINK | GTK_FILL),
                    (GtkAttachOptions) (0), 3, 3);
  gtk_entry_set_text (GTK_ENTRY (gtordestcall), _("NOCALL"));

  gtormycall = gtk_entry_new_with_max_length (12);
  gtk_widget_ref (gtormycall);
  gtk_object_set_data_full (GTK_OBJECT (wpar), "gtormycall", gtormycall,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (gtormycall);
  gtk_table_attach (GTK_TABLE (table5), gtormycall, 1, 2, 1, 2,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_SHRINK | GTK_FILL),
                    (GtkAttachOptions) (0), 3, 3);
  gtk_entry_set_text (GTK_ENTRY (gtormycall), _("NOCALL"));

  gtortxdelay = gtk_entry_new ();
  gtk_widget_ref (gtortxdelay);
  gtk_object_set_data_full (GTK_OBJECT (wpar), "gtortxdelay", gtortxdelay,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (gtortxdelay);
  gtk_table_attach (GTK_TABLE (table5), gtortxdelay, 1, 2, 2, 3,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_SHRINK | GTK_FILL),
                    (GtkAttachOptions) (0), 3, 3);
  gtk_entry_set_text (GTK_ENTRY (gtortxdelay), _("30"));

  gtorretry = gtk_entry_new ();
  gtk_widget_ref (gtorretry);
  gtk_object_set_data_full (GTK_OBJECT (wpar), "gtorretry", gtorretry,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (gtorretry);
  gtk_table_attach (GTK_TABLE (table5), gtorretry, 1, 2, 3, 4,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_SHRINK | GTK_FILL),
                    (GtkAttachOptions) (0), 3, 3);
  gtk_entry_set_text (GTK_ENTRY (gtorretry), _("30"));

  label23 = gtk_label_new (_("Destination Call"));
  gtk_widget_ref (label23);
  gtk_object_set_data_full (GTK_OBJECT (wpar), "label23", label23,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label23);
  gtk_table_attach (GTK_TABLE (table5), label23, 0, 1, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label23), 0, 0.5);
  gtk_misc_set_padding (GTK_MISC (label23), 5, 0);

  label24 = gtk_label_new (_("Mycall"));
  gtk_widget_ref (label24);
  gtk_object_set_data_full (GTK_OBJECT (wpar), "label24", label24,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label24);
  gtk_table_attach (GTK_TABLE (table5), label24, 0, 1, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label24), 0, 0.5);
  gtk_misc_set_padding (GTK_MISC (label24), 5, 0);

  label25 = gtk_label_new (_("TX Delay (ms)"));
  gtk_widget_ref (label25);
  gtk_object_set_data_full (GTK_OBJECT (wpar), "label25", label25,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label25);
  gtk_table_attach (GTK_TABLE (table5), label25, 0, 1, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label25), 0, 0.5);
  gtk_misc_set_padding (GTK_MISC (label25), 5, 0);

  label26 = gtk_label_new (_("Retries"));
  gtk_widget_ref (label26);
  gtk_object_set_data_full (GTK_OBJECT (wpar), "label26", label26,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label26);
  gtk_table_attach (GTK_TABLE (table5), label26, 0, 1, 3, 4,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label26), 0, 0.5);
  gtk_misc_set_padding (GTK_MISC (label26), 5, 0);

  label8 = gtk_label_new (_("GTOR"));
  gtk_widget_ref (label8);
  gtk_object_set_data_full (GTK_OBJECT (wpar), "label8", label8,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label8);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 4), label8);

  toolbar1 = gtk_toolbar_new (GTK_ORIENTATION_HORIZONTAL, GTK_TOOLBAR_TEXT);
  gtk_widget_ref (toolbar1);
  gtk_object_set_data_full (GTK_OBJECT (wpar), "toolbar1", toolbar1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (toolbar1);
  gtk_box_pack_start (GTK_BOX (vbox2), toolbar1, FALSE, FALSE, 0);

  parok = gtk_toolbar_append_element (GTK_TOOLBAR (toolbar1),
                                GTK_TOOLBAR_CHILD_BUTTON,
                                NULL,
                                _("OK"),
                                NULL, NULL,
                                NULL, NULL, NULL);
  gtk_widget_ref (parok);
  gtk_object_set_data_full (GTK_OBJECT (wpar), "parok", parok,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (parok);
  gtk_container_set_border_width (GTK_CONTAINER (parok), 3);

  parcancel = gtk_toolbar_append_element (GTK_TOOLBAR (toolbar1),
                                GTK_TOOLBAR_CHILD_BUTTON,
                                NULL,
                                _("Cancel"),
                                NULL, NULL,
                                NULL, NULL, NULL);
  gtk_widget_ref (parcancel);
  gtk_object_set_data_full (GTK_OBJECT (wpar), "parcancel", parcancel,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (parcancel);
  gtk_container_set_border_width (GTK_CONTAINER (parcancel), 3);

  gtk_signal_connect (GTK_OBJECT (wpar), "delete_event",
                      GTK_SIGNAL_FUNC (gtk_widget_hide),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (parok), "clicked",
                      GTK_SIGNAL_FUNC (on_parok_clicked),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (parcancel), "clicked",
                      GTK_SIGNAL_FUNC (on_parcancel_clicked),
                      NULL);

  return wpar;
}

GtkWidget*
create_wmain ()
{
  GtkWidget *wmain;
  GtkWidget *vbox3;
  GtkWidget *handlebox1;
  GtkWidget *menubar1;
  GtkWidget *file;
  GtkWidget *file_menu;
  GtkAccelGroup *file_menu_accels;
  GtkWidget *quit;
  GtkWidget *state;
  GtkWidget *state_menu;
  GtkAccelGroup *state_menu_accels;
  GtkWidget *become_irs;
  GtkWidget *become_iss;
  GtkWidget *qrt;
  GtkWidget *speedup;
  GtkWidget *uppercase;
  GtkWidget *lowercase;
  GtkWidget *figurecase;
  GtkWidget *mode;
  GtkWidget *mode_menu;
  GtkAccelGroup *mode_menu_accels;
  GtkWidget *standby;
  GtkWidget *pactor_arq;
  GtkWidget *pactor_fec;
  GtkWidget *gtor_arq1;
  GtkWidget *amtor_arq;
  GtkWidget *amtor_collective_fec;
  GtkWidget *amtor_selective_fec;
  GtkWidget *rtty_receive;
  GtkWidget *rtty_transmit;
  GtkWidget *utilities;
  GtkWidget *utilities_menu;
  GtkAccelGroup *utilities_menu_accels;
  GtkWidget *frequency_spectrum;
  GtkWidget *parameters;
  GtkWidget *monitor;
  GtkWidget *help;
  GtkWidget *help_menu;
  GtkAccelGroup *help_menu_accels;
  GtkWidget *about;
  GtkWidget *scrolledwindow1;
  GtkWidget *textmain;
  GtkWidget *frame4;
  GtkWidget *textedit;
  GtkWidget *scrolledwindow2;
  GtkWidget *textstatus;
  GtkAccelGroup *accel_group;
  GtkTooltips *tooltips;

  tooltips = gtk_tooltips_new ();

  accel_group = gtk_accel_group_new ();

  wmain = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_object_set_data (GTK_OBJECT (wmain), "wmain", wmain);
  gtk_window_set_title (GTK_WINDOW (wmain), _("Main Window"));
  gtk_window_set_policy (GTK_WINDOW (wmain), TRUE, TRUE, FALSE);
  gtk_window_set_wmclass (GTK_WINDOW (wmain), "hfterm", "hfterm");

  vbox3 = gtk_vbox_new (FALSE, 0);
  gtk_widget_ref (vbox3);
  gtk_object_set_data_full (GTK_OBJECT (wmain), "vbox3", vbox3,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (vbox3);
  gtk_container_add (GTK_CONTAINER (wmain), vbox3);

  handlebox1 = gtk_handle_box_new ();
  gtk_widget_ref (handlebox1);
  gtk_object_set_data_full (GTK_OBJECT (wmain), "handlebox1", handlebox1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (handlebox1);
  gtk_box_pack_start (GTK_BOX (vbox3), handlebox1, FALSE, TRUE, 0);

  menubar1 = gtk_menu_bar_new ();
  gtk_widget_ref (menubar1);
  gtk_object_set_data_full (GTK_OBJECT (wmain), "menubar1", menubar1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (menubar1);
  gtk_container_add (GTK_CONTAINER (handlebox1), menubar1);

  file = gtk_menu_item_new_with_label (_("File"));
  gtk_widget_ref (file);
  gtk_object_set_data_full (GTK_OBJECT (wmain), "file", file,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (file);
  gtk_container_add (GTK_CONTAINER (menubar1), file);

  file_menu = gtk_menu_new ();
  gtk_widget_ref (file_menu);
  gtk_object_set_data_full (GTK_OBJECT (wmain), "file_menu", file_menu,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_menu_item_set_submenu (GTK_MENU_ITEM (file), file_menu);
  file_menu_accels = gtk_menu_ensure_uline_accel_group (GTK_MENU (file_menu));

  quit = gtk_menu_item_new_with_label (_("Quit"));
  gtk_widget_ref (quit);
  gtk_object_set_data_full (GTK_OBJECT (wmain), "quit", quit,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (quit);
  gtk_container_add (GTK_CONTAINER (file_menu), quit);

  state = gtk_menu_item_new_with_label (_("State"));
  gtk_widget_ref (state);
  gtk_object_set_data_full (GTK_OBJECT (wmain), "state", state,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (state);
  gtk_container_add (GTK_CONTAINER (menubar1), state);

  state_menu = gtk_menu_new ();
  gtk_widget_ref (state_menu);
  gtk_object_set_data_full (GTK_OBJECT (wmain), "state_menu", state_menu,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_menu_item_set_submenu (GTK_MENU_ITEM (state), state_menu);
  state_menu_accels = gtk_menu_ensure_uline_accel_group (GTK_MENU (state_menu));

  become_irs = gtk_menu_item_new_with_label (_("Become IRS"));
  gtk_widget_ref (become_irs);
  gtk_object_set_data_full (GTK_OBJECT (wmain), "become_irs", become_irs,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (become_irs);
  gtk_container_add (GTK_CONTAINER (state_menu), become_irs);
  gtk_widget_add_accelerator (become_irs, "activate", accel_group,
                              GDK_r, GDK_MOD1_MASK,
                              GTK_ACCEL_VISIBLE);

  become_iss = gtk_menu_item_new_with_label (_("Become ISS"));
  gtk_widget_ref (become_iss);
  gtk_object_set_data_full (GTK_OBJECT (wmain), "become_iss", become_iss,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (become_iss);
  gtk_container_add (GTK_CONTAINER (state_menu), become_iss);
  gtk_widget_add_accelerator (become_iss, "activate", accel_group,
                              GDK_t, GDK_MOD1_MASK,
                              GTK_ACCEL_VISIBLE);

  qrt = gtk_menu_item_new_with_label (_("QRT"));
  gtk_widget_ref (qrt);
  gtk_object_set_data_full (GTK_OBJECT (wmain), "qrt", qrt,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (qrt);
  gtk_container_add (GTK_CONTAINER (state_menu), qrt);
  gtk_widget_add_accelerator (qrt, "activate", accel_group,
                              GDK_q, GDK_MOD1_MASK,
                              GTK_ACCEL_VISIBLE);

  speedup = gtk_menu_item_new_with_label (_("Speed Up"));
  gtk_widget_ref (speedup);
  gtk_object_set_data_full (GTK_OBJECT (wmain), "speedup", speedup,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (speedup);
  gtk_container_add (GTK_CONTAINER (state_menu), speedup);
  gtk_widget_add_accelerator (speedup, "activate", accel_group,
                              GDK_s, GDK_MOD1_MASK,
                              GTK_ACCEL_VISIBLE);

  uppercase = gtk_menu_item_new_with_label (_("Uppercase"));
  gtk_widget_ref (uppercase);
  gtk_object_set_data_full (GTK_OBJECT (wmain), "uppercase", uppercase,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (uppercase);
  gtk_container_add (GTK_CONTAINER (state_menu), uppercase);
  gtk_widget_add_accelerator (uppercase, "activate", accel_group,
                              GDK_u, GDK_MOD1_MASK,
                              GTK_ACCEL_VISIBLE);

  lowercase = gtk_menu_item_new_with_label (_("Lowercase"));
  gtk_widget_ref (lowercase);
  gtk_object_set_data_full (GTK_OBJECT (wmain), "lowercase", lowercase,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (lowercase);
  gtk_container_add (GTK_CONTAINER (state_menu), lowercase);
  gtk_widget_add_accelerator (lowercase, "activate", accel_group,
                              GDK_l, GDK_MOD1_MASK,
                              GTK_ACCEL_VISIBLE);

  figurecase = gtk_menu_item_new_with_label (_("Figurecase"));
  gtk_widget_ref (figurecase);
  gtk_object_set_data_full (GTK_OBJECT (wmain), "figurecase", figurecase,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (figurecase);
  gtk_container_add (GTK_CONTAINER (state_menu), figurecase);
  gtk_widget_add_accelerator (figurecase, "activate", accel_group,
                              GDK_f, GDK_MOD1_MASK,
                              GTK_ACCEL_VISIBLE);

  mode = gtk_menu_item_new_with_label (_("Mode"));
  gtk_widget_ref (mode);
  gtk_object_set_data_full (GTK_OBJECT (wmain), "mode", mode,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (mode);
  gtk_container_add (GTK_CONTAINER (menubar1), mode);

  mode_menu = gtk_menu_new ();
  gtk_widget_ref (mode_menu);
  gtk_object_set_data_full (GTK_OBJECT (wmain), "mode_menu", mode_menu,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_menu_item_set_submenu (GTK_MENU_ITEM (mode), mode_menu);
  mode_menu_accels = gtk_menu_ensure_uline_accel_group (GTK_MENU (mode_menu));

  standby = gtk_menu_item_new_with_label (_("Standby"));
  gtk_widget_ref (standby);
  gtk_object_set_data_full (GTK_OBJECT (wmain), "standby", standby,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (standby);
  gtk_container_add (GTK_CONTAINER (mode_menu), standby);
  gtk_widget_add_accelerator (standby, "activate", accel_group,
                              GDK_F2, 0,
                              GTK_ACCEL_VISIBLE);

  pactor_arq = gtk_menu_item_new_with_label (_("Pactor ARQ"));
  gtk_widget_ref (pactor_arq);
  gtk_object_set_data_full (GTK_OBJECT (wmain), "pactor_arq", pactor_arq,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (pactor_arq);
  gtk_container_add (GTK_CONTAINER (mode_menu), pactor_arq);
  gtk_widget_add_accelerator (pactor_arq, "activate", accel_group,
                              GDK_F3, 0,
                              GTK_ACCEL_VISIBLE);

  pactor_fec = gtk_menu_item_new_with_label (_("Pactor FEC"));
  gtk_widget_ref (pactor_fec);
  gtk_object_set_data_full (GTK_OBJECT (wmain), "pactor_fec", pactor_fec,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (pactor_fec);
  gtk_container_add (GTK_CONTAINER (mode_menu), pactor_fec);
  gtk_widget_add_accelerator (pactor_fec, "activate", accel_group,
                              GDK_F4, 0,
                              GTK_ACCEL_VISIBLE);

  gtor_arq1 = gtk_menu_item_new_with_label (_("GTOR ARQ"));
  gtk_widget_ref (gtor_arq1);
  gtk_object_set_data_full (GTK_OBJECT (wmain), "gtor_arq1", gtor_arq1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (gtor_arq1);
  gtk_container_add (GTK_CONTAINER (mode_menu), gtor_arq1);
  gtk_widget_add_accelerator (gtor_arq1, "activate", accel_group,
                              GDK_F5, 0,
                              GTK_ACCEL_VISIBLE);

  amtor_arq = gtk_menu_item_new_with_label (_("Amtor ARQ"));
  gtk_widget_ref (amtor_arq);
  gtk_object_set_data_full (GTK_OBJECT (wmain), "amtor_arq", amtor_arq,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (amtor_arq);
  gtk_container_add (GTK_CONTAINER (mode_menu), amtor_arq);
  gtk_widget_add_accelerator (amtor_arq, "activate", accel_group,
                              GDK_F6, 0,
                              GTK_ACCEL_VISIBLE);

  amtor_collective_fec = gtk_menu_item_new_with_label (_("Amtor Collective FEC"));
  gtk_widget_ref (amtor_collective_fec);
  gtk_object_set_data_full (GTK_OBJECT (wmain), "amtor_collective_fec", amtor_collective_fec,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (amtor_collective_fec);
  gtk_container_add (GTK_CONTAINER (mode_menu), amtor_collective_fec);
  gtk_widget_add_accelerator (amtor_collective_fec, "activate", accel_group,
                              GDK_F7, 0,
                              GTK_ACCEL_VISIBLE);

  amtor_selective_fec = gtk_menu_item_new_with_label (_("Amtor Selective FEC"));
  gtk_widget_ref (amtor_selective_fec);
  gtk_object_set_data_full (GTK_OBJECT (wmain), "amtor_selective_fec", amtor_selective_fec,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (amtor_selective_fec);
  gtk_container_add (GTK_CONTAINER (mode_menu), amtor_selective_fec);
  gtk_widget_add_accelerator (amtor_selective_fec, "activate", accel_group,
                              GDK_F8, 0,
                              GTK_ACCEL_VISIBLE);

  rtty_receive = gtk_menu_item_new_with_label (_("RTTY Receive"));
  gtk_widget_ref (rtty_receive);
  gtk_object_set_data_full (GTK_OBJECT (wmain), "rtty_receive", rtty_receive,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (rtty_receive);
  gtk_container_add (GTK_CONTAINER (mode_menu), rtty_receive);
  gtk_widget_add_accelerator (rtty_receive, "activate", accel_group,
                              GDK_F9, 0,
                              GTK_ACCEL_VISIBLE);

  rtty_transmit = gtk_menu_item_new_with_label (_("RTTY Transmit"));
  gtk_widget_ref (rtty_transmit);
  gtk_object_set_data_full (GTK_OBJECT (wmain), "rtty_transmit", rtty_transmit,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (rtty_transmit);
  gtk_container_add (GTK_CONTAINER (mode_menu), rtty_transmit);
  gtk_widget_add_accelerator (rtty_transmit, "activate", accel_group,
                              GDK_F10, 0,
                              GTK_ACCEL_VISIBLE);

  utilities = gtk_menu_item_new_with_label (_("Utilities"));
  gtk_widget_ref (utilities);
  gtk_object_set_data_full (GTK_OBJECT (wmain), "utilities", utilities,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (utilities);
  gtk_container_add (GTK_CONTAINER (menubar1), utilities);

  utilities_menu = gtk_menu_new ();
  gtk_widget_ref (utilities_menu);
  gtk_object_set_data_full (GTK_OBJECT (wmain), "utilities_menu", utilities_menu,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_menu_item_set_submenu (GTK_MENU_ITEM (utilities), utilities_menu);
  utilities_menu_accels = gtk_menu_ensure_uline_accel_group (GTK_MENU (utilities_menu));

  frequency_spectrum = gtk_menu_item_new_with_label (_("Frequency Spectrum"));
  gtk_widget_ref (frequency_spectrum);
  gtk_object_set_data_full (GTK_OBJECT (wmain), "frequency_spectrum", frequency_spectrum,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (frequency_spectrum);
  gtk_container_add (GTK_CONTAINER (utilities_menu), frequency_spectrum);

  parameters = gtk_menu_item_new_with_label (_("Parameters"));
  gtk_widget_ref (parameters);
  gtk_object_set_data_full (GTK_OBJECT (wmain), "parameters", parameters,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (parameters);
  gtk_container_add (GTK_CONTAINER (utilities_menu), parameters);

  monitor = gtk_menu_item_new_with_label (_("Monitor"));
  gtk_widget_ref (monitor);
  gtk_object_set_data_full (GTK_OBJECT (wmain), "monitor", monitor,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (monitor);
  gtk_container_add (GTK_CONTAINER (utilities_menu), monitor);

  help = gtk_menu_item_new_with_label (_("Help"));
  gtk_widget_ref (help);
  gtk_object_set_data_full (GTK_OBJECT (wmain), "help", help,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (help);
  gtk_container_add (GTK_CONTAINER (menubar1), help);
  gtk_menu_item_right_justify (GTK_MENU_ITEM (help));

  help_menu = gtk_menu_new ();
  gtk_widget_ref (help_menu);
  gtk_object_set_data_full (GTK_OBJECT (wmain), "help_menu", help_menu,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_menu_item_set_submenu (GTK_MENU_ITEM (help), help_menu);
  help_menu_accels = gtk_menu_ensure_uline_accel_group (GTK_MENU (help_menu));

  about = gtk_menu_item_new_with_label (_("About"));
  gtk_widget_ref (about);
  gtk_object_set_data_full (GTK_OBJECT (wmain), "about", about,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (about);
  gtk_container_add (GTK_CONTAINER (help_menu), about);

  scrolledwindow1 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_ref (scrolledwindow1);
  gtk_object_set_data_full (GTK_OBJECT (wmain), "scrolledwindow1", scrolledwindow1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (scrolledwindow1);
  gtk_box_pack_start (GTK_BOX (vbox3), scrolledwindow1, TRUE, TRUE, 0);
  gtk_scrolled_window_set_policy (GTK_SCROLLED_WINDOW (scrolledwindow1), GTK_POLICY_NEVER, GTK_POLICY_ALWAYS);

  textmain = gtk_text_new (NULL, NULL);
  gtk_widget_ref (textmain);
  gtk_object_set_data_full (GTK_OBJECT (wmain), "textmain", textmain,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (textmain);
  gtk_container_add (GTK_CONTAINER (scrolledwindow1), textmain);
  gtk_widget_set_usize (textmain, 512, 300);
  GTK_WIDGET_UNSET_FLAGS (textmain, GTK_CAN_FOCUS);
  gtk_widget_set_events (textmain, GDK_KEY_PRESS_MASK | GDK_KEY_RELEASE_MASK);

  frame4 = gtk_frame_new (_("Transmit Text Entry"));
  gtk_widget_ref (frame4);
  gtk_object_set_data_full (GTK_OBJECT (wmain), "frame4", frame4,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (frame4);
  gtk_box_pack_start (GTK_BOX (vbox3), frame4, FALSE, TRUE, 0);

  textedit = gtk_entry_new ();
  gtk_widget_ref (textedit);
  gtk_object_set_data_full (GTK_OBJECT (wmain), "textedit", textedit,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (textedit);
  gtk_container_add (GTK_CONTAINER (frame4), textedit);
  gtk_widget_set_events (textedit, GDK_KEY_PRESS_MASK | GDK_KEY_RELEASE_MASK);
  gtk_entry_set_editable (GTK_ENTRY (textedit), FALSE);

  scrolledwindow2 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_ref (scrolledwindow2);
  gtk_object_set_data_full (GTK_OBJECT (wmain), "scrolledwindow2", scrolledwindow2,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (scrolledwindow2);
  gtk_box_pack_start (GTK_BOX (vbox3), scrolledwindow2, FALSE, FALSE, 0);
  gtk_scrolled_window_set_policy (GTK_SCROLLED_WINDOW (scrolledwindow2), GTK_POLICY_NEVER, GTK_POLICY_ALWAYS);

  textstatus = gtk_text_new (NULL, NULL);
  gtk_widget_ref (textstatus);
  gtk_object_set_data_full (GTK_OBJECT (wmain), "textstatus", textstatus,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (textstatus);
  gtk_container_add (GTK_CONTAINER (scrolledwindow2), textstatus);
  gtk_widget_set_usize (textstatus, -2, 120);
  GTK_WIDGET_UNSET_FLAGS (textstatus, GTK_CAN_FOCUS);
  gtk_tooltips_set_tip (tooltips, textstatus, _("Status Display"), NULL);
  gtk_widget_realize (textstatus);
  gtk_text_insert (GTK_TEXT (textstatus), NULL, NULL, NULL,
                   _("1\n2\n3\n4\n5\n6\n7\n8"), 15);

  gtk_signal_connect (GTK_OBJECT (wmain), "delete_event",
                      GTK_SIGNAL_FUNC (on_wmain_delete_event),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (wmain), "destroy_event",
                      GTK_SIGNAL_FUNC (on_wmain_destroy_event),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (quit), "activate",
                      GTK_SIGNAL_FUNC (on_quit_activate),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (become_irs), "activate",
                      GTK_SIGNAL_FUNC (on_become_irs_activate),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (become_iss), "activate",
                      GTK_SIGNAL_FUNC (on_become_iss_activate),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (qrt), "activate",
                      GTK_SIGNAL_FUNC (on_qrt_activate),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (speedup), "activate",
                      GTK_SIGNAL_FUNC (on_speedup_activate),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (uppercase), "activate",
                      GTK_SIGNAL_FUNC (on_uppercase_activate),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (lowercase), "activate",
                      GTK_SIGNAL_FUNC (on_lowercase_activate),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (figurecase), "activate",
                      GTK_SIGNAL_FUNC (on_figurecase_activate),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (standby), "activate",
                      GTK_SIGNAL_FUNC (on_standby_activate),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (pactor_arq), "activate",
                      GTK_SIGNAL_FUNC (on_pactor_arq_activate),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (pactor_fec), "activate",
                      GTK_SIGNAL_FUNC (on_pactor_fec_activate),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (gtor_arq1), "activate",
                      GTK_SIGNAL_FUNC (on_gtor_arq1_activate),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (amtor_arq), "activate",
                      GTK_SIGNAL_FUNC (on_amtor_arq_activate),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (amtor_collective_fec), "activate",
                      GTK_SIGNAL_FUNC (on_amtor_collective_fec_activate),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (amtor_selective_fec), "activate",
                      GTK_SIGNAL_FUNC (on_amtor_selective_fec_activate),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (rtty_receive), "activate",
                      GTK_SIGNAL_FUNC (on_rtty_receive_activate),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (rtty_transmit), "activate",
                      GTK_SIGNAL_FUNC (on_rtty_transmit_activate),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (frequency_spectrum), "activate",
                      GTK_SIGNAL_FUNC (on_frequency_spectrum_activate),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (parameters), "activate",
                      GTK_SIGNAL_FUNC (on_parameters_activate),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (monitor), "activate",
                      GTK_SIGNAL_FUNC (on_monitor_activate),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (about), "activate",
                      GTK_SIGNAL_FUNC (on_about_activate),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (textmain), "key_press_event",
                      GTK_SIGNAL_FUNC (on_text_keypress_event),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (textmain), "key_release_event",
                      GTK_SIGNAL_FUNC (on_text_keyrelease_event),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (textedit), "key_press_event",
                      GTK_SIGNAL_FUNC (on_text_keypress_event),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (textedit), "key_release_event",
                      GTK_SIGNAL_FUNC (on_text_keyrelease_event),
                      NULL);

  gtk_widget_grab_focus (textedit);
  gtk_object_set_data (GTK_OBJECT (wmain), "tooltips", tooltips);

  gtk_window_add_accel_group (GTK_WINDOW (wmain), accel_group);

  return wmain;
}

GtkWidget*
create_wabout ()
{
  GtkWidget *wabout;
  GtkWidget *vbox4;
  GtkWidget *vbox5;
  GtkWidget *label29;
  GtkWidget *label30;
  GtkWidget *hbuttonbox1;
  GtkWidget *button1;

  wabout = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_object_set_data (GTK_OBJECT (wabout), "wabout", wabout);
  gtk_window_set_title (GTK_WINDOW (wabout), _("About hfterm..."));
  gtk_window_set_wmclass (GTK_WINDOW (wabout), "hfterm", "hfterm");

  vbox4 = gtk_vbox_new (FALSE, 0);
  gtk_widget_ref (vbox4);
  gtk_object_set_data_full (GTK_OBJECT (wabout), "vbox4", vbox4,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (vbox4);
  gtk_container_add (GTK_CONTAINER (wabout), vbox4);

  vbox5 = gtk_vbox_new (FALSE, 0);
  gtk_widget_ref (vbox5);
  gtk_object_set_data_full (GTK_OBJECT (wabout), "vbox5", vbox5,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (vbox5);
  gtk_box_pack_start (GTK_BOX (vbox4), vbox5, TRUE, TRUE, 0);

  label29 = gtk_label_new (_("HFTERM"));
  gtk_widget_ref (label29);
  gtk_object_set_data_full (GTK_OBJECT (wabout), "label29", label29,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label29);
  gtk_box_pack_start (GTK_BOX (vbox5), label29, TRUE, TRUE, 0);

  label30 = gtk_label_new (_("(C) 1999 Thomas Sailer, HB9JNX/AE4WA"));
  gtk_widget_ref (label30);
  gtk_object_set_data_full (GTK_OBJECT (wabout), "label30", label30,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label30);
  gtk_box_pack_start (GTK_BOX (vbox5), label30, TRUE, TRUE, 0);

  hbuttonbox1 = gtk_hbutton_box_new ();
  gtk_widget_ref (hbuttonbox1);
  gtk_object_set_data_full (GTK_OBJECT (wabout), "hbuttonbox1", hbuttonbox1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hbuttonbox1);
  gtk_box_pack_start (GTK_BOX (vbox4), hbuttonbox1, FALSE, TRUE, 5);

  button1 = gtk_button_new_with_label (_("OK"));
  gtk_widget_ref (button1);
  gtk_object_set_data_full (GTK_OBJECT (wabout), "button1", button1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (button1);
  gtk_container_add (GTK_CONTAINER (hbuttonbox1), button1);
  GTK_WIDGET_SET_FLAGS (button1, GTK_CAN_DEFAULT);

  gtk_signal_connect (GTK_OBJECT (wabout), "delete_event",
                      GTK_SIGNAL_FUNC (gtk_widget_hide),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (button1), "clicked",
                      GTK_SIGNAL_FUNC (on_aboutok_clicked),
                      NULL);

  return wabout;
}

GtkWidget*
create_wmonitor ()
{
  GtkWidget *wmonitor;
  GtkWidget *scrolledwindow3;
  GtkWidget *textmonitor;

  wmonitor = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_object_set_data (GTK_OBJECT (wmonitor), "wmonitor", wmonitor);
  gtk_window_set_title (GTK_WINDOW (wmonitor), _("Monitor"));
  gtk_window_set_policy (GTK_WINDOW (wmonitor), TRUE, TRUE, FALSE);

  scrolledwindow3 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_ref (scrolledwindow3);
  gtk_object_set_data_full (GTK_OBJECT (wmonitor), "scrolledwindow3", scrolledwindow3,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (scrolledwindow3);
  gtk_container_add (GTK_CONTAINER (wmonitor), scrolledwindow3);
  gtk_scrolled_window_set_policy (GTK_SCROLLED_WINDOW (scrolledwindow3), GTK_POLICY_NEVER, GTK_POLICY_ALWAYS);

  textmonitor = gtk_text_new (NULL, NULL);
  gtk_widget_ref (textmonitor);
  gtk_object_set_data_full (GTK_OBJECT (wmonitor), "textmonitor", textmonitor,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (textmonitor);
  gtk_container_add (GTK_CONTAINER (scrolledwindow3), textmonitor);
  gtk_widget_set_usize (textmonitor, 512, 300);

  gtk_signal_connect (GTK_OBJECT (wmonitor), "delete_event",
                      GTK_SIGNAL_FUNC (gtk_widget_hide),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (textmonitor), "delete_event",
                      GTK_SIGNAL_FUNC (gtk_widget_hide),
                      NULL);

  return wmonitor;
}

